apiVersion: apps/v1
kind: Deployment
metadata:
  name: upload-service
  labels:
    app: upload-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: upload-service
  template:
    metadata:
      labels:
        app: upload-service
    spec:
      containers:
      - name: upload-service
        image: jpalaparthi/uploadimage:latest   # Replace with your Docker image
        ports:
        - containerPort: 9090
          name: http
        env:
        - name: PORT
          valueFrom:
           configMapKeyRef:
            name: upload-service-cm
            key: PORT
        - name: PASSWORD
          valueFrom:
            secretKeyRef:
              name: mysecret
              key: password

            
        volumeMounts:
        - name: upload-storage
          mountPath: /app/uploads
      volumes:
      - name: upload-storage
        persistentVolumeClaim:
          claimName: upload-pvc
---
apiVersion: v1
kind: Service
metadata:
  name: upload-service
spec:
  selector:
    app: upload-service
  ports:
    - protocol: TCP
      port: 80
      targetPort: 9090
  type: LoadBalancer