apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  namespace: kube-system
spec:
  selector:
    matchLabels:
      name:  nginx-daemonset
  template:
    metadata:
      labels:
        name:  nginx-daemonset
    spec:
      containers:
      - name:  nginx-daemonset
        image:  nginx:1.15
        resources:
          limits:
            memory: 200Mi
          requests:
            cpu: 100m
            memory: 200Mi
        ports:
        - containerPort: 80
      

