FROM golang:1.22-alpine as build

WORKDIR /app

COPY . .

# RUN go mod download

RUN CGO_ENABLED=0 GOOS=linux go build -ldflags="-s -w" -o app main.go

FROM scratch

WORKDIR /root

COPY --from=build /app/app .

EXPOSE 8080

CMD ["./app"]
